from __future__ import annotations

import os
from typing import Any

VERSION = "0.1.0"


def base_url() -> str:
    return (os.environ.get("BASE_URL") or "http://127.0.0.1:8770").rstrip("/")


def tools(latency: dict[str, float] | None = None) -> list[dict[str, Any]]:
    lat = latency or {}
    b = base_url()
    return [
        {
            "service_id": "agent-json-reliability.validate",
            "product_family": "AGENT_JSON_RELIABILITY",
            "tool_name": "validate_json",
            "description": "Validate a JSON instance against a supplied JSON Schema and return structured validation errors. Deterministic. No LLM.",
            "path": "/v1/json/validate",
            "method": "POST",
            "resource": f"{b}/v1/json/validate",
            "input_schema": {
                "type": "object",
                "required": ["instance"],
                "properties": {"instance": {}, "schema": {"type": "object"}},
            },
            "output_schema": {
                "type": "object",
                "properties": {
                    "ok": {"type": "boolean"},
                    "valid_json": {"type": "boolean"},
                    "schema_valid": {"type": ["boolean", "null"]},
                    "errors": {"type": "array"},
                    "error_count": {"type": "integer"},
                    "processing_ms": {"type": "number"},
                },
            },
            "examples": [{"input": {"instance": {"name": "a"}, "schema": {"type": "object", "required": ["name"]}}, "output": {"ok": True}}],
            "limitations": "No remote $ref. Size and depth limits. Does not execute code.",
            "capabilities": ["json", "schema", "validate", "validation"],
            "input_type": "json_instance_and_schema",
            "output_type": "validation_report",
            "deterministic": True,
            "latency_ms_p50": lat.get("json_p50"),
            "marginal_cost_class": "NEAR_ZERO",
            "future_market_price_usd": 0.005,
            "free_beta": True,
            "payment_required": False,
            "version": VERSION,
        },
        {
            "service_id": "agent-json-reliability.repair",
            "product_family": "AGENT_JSON_RELIABILITY",
            "tool_name": "repair_json",
            "description": "Safely repair common malformed JSON generated by software and AI agents without inventing missing semantic values.",
            "path": "/v1/json/repair",
            "method": "POST",
            "resource": f"{b}/v1/json/repair",
            "input_schema": {"type": "object", "required": ["text"], "properties": {"text": {"type": "string"}, "mode": {"type": "string"}}},
            "output_schema": {"type": "object", "properties": {"repaired": {"type": "boolean"}, "json": {}, "changes": {"type": "array"}, "unsafe_or_ambiguous": {"type": "boolean"}}},
            "examples": [{"input": {"text": "{'a': 1}"}, "output": {"repaired": True, "json": {"a": 1}}}],
            "limitations": "Refuses ambiguous repairs. Not an LLM rewriter.",
            "capabilities": ["json", "repair", "malformed", "fix"],
            "input_type": "text",
            "output_type": "json",
            "deterministic": True,
            "latency_ms_p50": lat.get("json_p50"),
            "marginal_cost_class": "NEAR_ZERO",
            "future_market_price_usd": 0.005,
            "free_beta": True,
            "payment_required": False,
            "version": VERSION,
        },
        {
            "service_id": "agent-json-reliability.inspect",
            "product_family": "AGENT_JSON_RELIABILITY",
            "tool_name": "inspect_json",
            "description": "Diagnose whether text is JSON, likely failure types, error position, and whether safe repair is possible. Deterministic. No LLM.",
            "path": "/v1/json/inspect",
            "method": "POST",
            "resource": f"{b}/v1/json/inspect",
            "input_schema": {"type": "object", "required": ["text"], "properties": {"text": {"type": "string"}}},
            "output_schema": {"type": "object", "properties": {"valid_json": {"type": "boolean"}, "detected_failure_types": {"type": "array"}, "repair_possible": {"type": "boolean"}}},
            "examples": [{"input": {"text": "{a:1}"}, "output": {"valid_json": False}}],
            "limitations": "Diagnostic only; does not mutate the value unless repair is called.",
            "capabilities": ["json", "inspect", "diagnose"],
            "input_type": "text",
            "output_type": "diagnostics",
            "deterministic": True,
            "latency_ms_p50": lat.get("json_p50"),
            "marginal_cost_class": "NEAR_ZERO",
            "future_market_price_usd": 0.001,
            "free_beta": True,
            "payment_required": False,
            "version": VERSION,
        },
        {
            "service_id": "agent-json-reliability.reliable",
            "product_family": "AGENT_JSON_RELIABILITY",
            "tool_name": "reliable_json",
            "description": "Inspect text, safely repair malformed JSON if needed, then optionally validate against a JSON Schema. Deterministic pipeline. No LLM.",
            "path": "/v1/json/reliable",
            "method": "POST",
            "resource": f"{b}/v1/json/reliable",
            "input_schema": {"type": "object", "required": ["text"], "properties": {"text": {"type": "string"}, "schema": {"type": "object"}}},
            "output_schema": {"type": "object", "properties": {"valid_original": {"type": "boolean"}, "repaired": {"type": "boolean"}, "valid_final": {"type": "boolean"}, "schema_valid": {"type": ["boolean", "null"]}}},
            "examples": [{"input": {"text": "{'name': 'a'}", "schema": {"type": "object"}}, "output": {"valid_final": True}}],
            "limitations": "Same repair refusal rules. Schema validation has no remote $ref.",
            "capabilities": ["json", "repair", "validate", "schema", "pipeline"],
            "input_type": "text_and_optional_schema",
            "output_type": "json_reliability_report",
            "deterministic": True,
            "latency_ms_p50": lat.get("json_p50"),
            "marginal_cost_class": "NEAR_ZERO",
            "future_market_price_usd": 0.005,
            "free_beta": True,
            "payment_required": False,
            "version": VERSION,
        }
    ]


def catalog_payload(latency: dict[str, float] | None = None) -> dict[str, Any]:
    ts = tools(latency)
    return {
        "version": VERSION,
        "payment_required": False,
        "free_beta": True,
        "x402_payments": False,
        "base_url": base_url(),
        "services": ts,
        "products": [
            {"id": "AGENT_JSON_RELIABILITY", "tools": [t["tool_name"] for t in ts if t["product_family"] == "AGENT_JSON_RELIABILITY"]},
        ],
    }
